### ISSUE TITLE
返回上一个页面  $route 值不对 ,还是被销毁的页面

### ISSUE THREAD

**Issue by DestinyHunter** [geminate/megalo-router-patch#1]
rt

**Comment by geminate** [comment]
感谢反馈
修复过程中，尝试将 created 混入修改为 onShow 混入，但由于 megalo 框架自身的 onShow 生命周期混入 存在bug。
需要等待 megalo 官方修复此问题。

**Comment by geminate** [comment]
请关注 [https://github.com/kaola-fed/megalo/issues/73](https://github.com/kaola-fed/megalo/issues/73)


现阶段建议使用框架写法 this.$root.$mp

**Comment by geminate** [comment]
问题已解决
需要升级 megalo 至 0.6.0 或以上版本
megalo-router-patch 0.1.4 或以上版本
